### ISSUE TITLE
trying to launch but noting happens after that 

### ISSUE THREAD

**Issue by GGLVXD** [BedrockLauncher/BedrockLauncher#415]
here are logs 
https://pastebin.com/U0ELr5f0

**Comment by Rayth** [comment]
Can you try reinstalling the .NET DESKTOP runtime from here: https://dotnet.microsoft.com/en-us/download/dotnet/6.0

If that doesn't work, try installing minecraft from the official store/launcher, run it once, then uninstall it and try our launcher.

**Comment by Coder4562** [comment]
I found a way to fix this issue and that is go into the directory for the launcher itself and modify the json file called settings and set isfirstlaunch to false. this will make the launcher load the game that you already own and run it as an existing user. The settings.json file is located inside the data folder in the Bedrock launcher directory this should fix the issue because it worked for me and got the game running, I hope this helps fix your issue.

**Comment by Rayth** [comment]
> I found a way to fix this issue and that is go into the directory for the launcher itself and modify the json file called settings and set isfirstlaunch to false. this will make the launcher load the game that you already own and run it as an existing user. The settings.json file is located inside the data folder in the Bedrock launcher directory this should fix the issue because it worked for me and got the game running, I hope this helps fix your issue.

This isn't a fix, it's a work around, and is a work around  we stopped telling people to do months ago because it didn't actually solve the issue. All this does is skip the initial setup phase, at which point you can lose data if you didn't manually backup your mc stuff before hand.

**Comment by Rayth** [comment]
Closing due to inactivity from OP
